spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    redis:
      username: ${REDIS_USER:default}
      password: ${REDIS_PASSWORD:redis}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  liquibase:
    contexts: dev