spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  data:
    redis:
      url: redis://localhost:6379
  jpa:
    show-sql: true
  liquibase:
    contexts: dev
jwt:
  secret: cee86fe38f76573ccb30716aaf318cf6073f48e6cd4cf1f66c04139e95e47af6
cors:
  host: http://localhost:8080