spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      url: redis://${REDIS_URI}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  jpa:
    show-sql: false
  liquibase:
    contexts: prod
jwt:
  secret: ${JWT_SECRET}
cors:
  host: ${CORS_HOST}
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  url: ${AWS_URL}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}